config/routes.rb
Rails.application.routes.draw do
  resources :productlists
  get '/productlists', :to => 'productlists#index'
  resources :customerreviews do
    resources :customerreviewtags
  end
  resources :tagcreations do
  collection do 
    get :export
    post :import , only: %w(import), controller: "tagcreations"
  end
end


  get '/tagcreations', :to => 'tagcreations#index'
  get '/products', :to => 'products#index'
  root :to => 'home#index'

  resource :marketing_activities, only: [:create, :update] do
    patch :resume
    patch :pause
    patch :delete
    post :republish
    post :preload_form_data
    post :preview
    post :errors
  end
  mount ShopifyApp::Engine, at: '/'
# frozen_string_literal: true

namespace :app_proxy do
  root action: 'index'
  # simple routes without a specified controller will go to AppProxyController

  # more complex routes will go to controllers in the AppProxy namespace
  #   resources :reviews
  # GET /app_proxy/reviews will now be routed to
  # AppProxy::ReviewsController#index, for example
end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/productlist.rb
class Productlist < ApplicationRecord
end

app/controllers/productlists_controller.rb
class ProductlistsController < ApplicationController
  before_action :set_productlist, only: [:show, :edit, :update, :destroy]

  # GET /productlists
  # GET /productlists.json
  def index
    @productlists = Productlist.all
  end

  # GET /productlists/1
  # GET /productlists/1.json
  def show
  end

  # GET /productlists/new
  def new
    @productlist = Productlist.new
  end

  # GET /productlists/1/edit
  def edit
  end

  # POST /productlists
  # POST /productlists.json
  def create
    @productlist = Productlist.new(productlist_params)

    respond_to do |format|
      if @productlist.save
        format.html { redirect_to @productlist, notice: 'Productlist was successfully created.' }
        format.json { render :show, status: :created, location: @productlist }
      else
        format.html { render :new }
        format.json { render json: @productlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /productlists/1
  # PATCH/PUT /productlists/1.json
  def update
    respond_to do |format|
      if @productlist.update(productlist_params)
        format.html { redirect_to @productlist, notice: 'Productlist was successfully updated.' }
        format.json { render :show, status: :ok, location: @productlist }
      else
        format.html { render :edit }
        format.json { render json: @productlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /productlists/1
  # DELETE /productlists/1.json
  def destroy
    @productlist.destroy
    respond_to do |format|
      format.html { redirect_to productlists_url, notice: 'Productlist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_productlist
      @productlist = Productlist.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def productlist_params
      params.require(:productlist).permit(:title, :body, :option1, :option2, :option3, :option1val, :option2val, :option3val)
    end
end

app/helpers/productlists_helper.rb
module ProductlistsHelper
end

app/views/productlists/_form.html.erb
<%= form_with(model: productlist, local: true) do |form| %>
  <% if productlist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(productlist.errors.count, "error") %> prohibited this productlist from being saved:</h2>

      <ul>
        <% productlist.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_field :body %>
  </div>

  <div class="field">
    <%= form.label :option1 %>
    <%= form.text_field :option1 %>
  </div>

  <div class="field">
    <%= form.label :option2 %>
    <%= form.text_field :option2 %>
  </div>

  <div class="field">
    <%= form.label :option3 %>
    <%= form.text_field :option3 %>
  </div>

  <div class="field">
    <%= form.label :option1val %>
    <%= form.text_field :option1val %>
  </div>

  <div class="field">
    <%= form.label :option2val %>
    <%= form.text_field :option2val %>
  </div>

  <div class="field">
    <%= form.label :option3val %>
    <%= form.text_field :option3val %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/productlists/edit.html.erb
<h1>Editing Productlist</h1>

<%= render 'form', productlist: @productlist %>

<%= link_to 'Show', @productlist %> |
<%= link_to 'Back', productlists_path %>

app/views/productlists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Productlists</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th>Option1</th>
      <th>Option2</th>
      <th>Option3</th>
      <th>Option1val</th>
      <th>Option2val</th>
      <th>Option3val</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @productlists.each do |productlist| %>
      <tr>
        <td><%= productlist.title %></td>
        <td><%= productlist.body %></td>
        <td><%= productlist.option1 %></td>
        <td><%= productlist.option2 %></td>
        <td><%= productlist.option3 %></td>
        <td><%= productlist.option1val %></td>
        <td><%= productlist.option2val %></td>
        <td><%= productlist.option3val %></td>
        <td><%= link_to 'Show', productlist %></td>
        <td><%= link_to 'Edit', edit_productlist_path(productlist) %></td>
        <td><%= link_to 'Destroy', productlist, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Productlist', new_productlist_path %>

app/views/productlists/new.html.erb
<h1>New Productlist</h1>

<%= render 'form', productlist: @productlist %>

<%= link_to 'Back', productlists_path %>

app/views/productlists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @productlist.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @productlist.body %>
</p>

<p>
  <strong>Option1:</strong>
  <%= @productlist.option1 %>
</p>

<p>
  <strong>Option2:</strong>
  <%= @productlist.option2 %>
</p>

<p>
  <strong>Option3:</strong>
  <%= @productlist.option3 %>
</p>

<p>
  <strong>Option1val:</strong>
  <%= @productlist.option1val %>
</p>

<p>
  <strong>Option2val:</strong>
  <%= @productlist.option2val %>
</p>

<p>
  <strong>Option3val:</strong>
  <%= @productlist.option3val %>
</p>

<%= link_to 'Edit', edit_productlist_path(@productlist) %> |
<%= link_to 'Back', productlists_path %>