config/routes.rb
Rails.application.routes.draw do
  resources :productlists
  get '/productlists', :to => 'productlists#index'
  resources :customerreviews do
    resources :customerreviewtags
  end
  resources :tagcreations do
  collection do 
    get :export
    post :import , only: %w(import), controller: "tagcreations"
  end
end


  get '/tagcreations', :to => 'tagcreations#index'
  get '/products', :to => 'products#index'
  root :to => 'home#index'

  resource :marketing_activities, only: [:create, :update] do
    patch :resume
    patch :pause
    patch :delete
    post :republish
    post :preload_form_data
    post :preview
    post :errors
  end
  mount ShopifyApp::Engine, at: '/'
# frozen_string_literal: true

namespace :app_proxy do
  root action: 'index'
  # simple routes without a specified controller will go to AppProxyController

  # more complex routes will go to controllers in the AppProxy namespace
  #   resources :reviews
  # GET /app_proxy/reviews will now be routed to
  # AppProxy::ReviewsController#index, for example
end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/customerreviews_controller.rb
class CustomerreviewsController < ApplicationController
  before_action :set_customerreview, only: [:show, :edit, :update, :destroy]
  # GET /customerreviews
  # GET /customerreviews.json
  def index
   
    @tagcreations = Tagcreation.paginate(page: params[:page], per_page: 6)    
     if params[:search]
      @search_term = params[:search]
      @tagcreations =@tagcreations.search_by(@search_term)
    end
  end

  # GET /customerreviews/1
  # GET /customerreviews/1.json
  def show
  end

  # GET /customerreviews/new
  def new
    @customerreview = Customerreview.new()
    @customerreview.Customerreviewtags.build
     @tagcreations = Tagcreation.where(id:15)
   end

  # GET /customerreviews/1/edit
  def edit
  end

  # POST /customerreviews
  # POST /customerreviews.json
  def create
    @customerreview = Customerreview.new(customerreview_params)
    respond_to do |format|
      if @customerreview.save
        format.html { redirect_to @customerreview, notice: 'Customerreview was successfully created.' }
        format.json { render :index, status: :created, location: @customerreview }
      else
        format.html { render :new }
        format.json { render json: @customerreview.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customerreviews/1
  # PATCH/PUT /customerreviews/1.json
  def update
    respond_to do |format|
      if @customerreview.update(customerreview_params)
        format.html { redirect_to @customerreview, notice: 'Customerreview was successfully updated.' }
        format.json { render :index, status: :ok, location: @customerreview }
      else
        format.html { render :edit }
        format.json { render json: @customerreview.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customerreviews/1
  # DELETE /customerreviews/1.json
  def destroy
    @customerreview.destroy
   
    respond_to do |format|
      format.html { redirect_to customerreviews_url, notice: 'Customerreview was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customerreview
      @customerreview = Customerreview.find(params[:id])
    end
    # Only allow a list of trusted parameters through.
    def customerreview_params
      params.require(:customerreview).permit(:customertype, :customername, :customeremail, :reviewrating, :reviewbody, :publish, :productid, :reviewid, customerreviewtags_attributes: [:producttag])
    end
end

app/helpers/customerreviews_helper.rb
module CustomerreviewsHelper
end

app/views/customerreviews/_form.html.erb
<%= form_with(model: [@tagcreation, customerreview], local: true) do |form| %>
  <% if customerreview.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(customerreview.errors.count, "error") %> prohibited this customerreview from being saved:</h2>

      <ul>
        <% customerreview.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<table border ="1" ><tr><td colspan="3" align ="center">Product Details</td></tr> 
  <% @tagcreations.each do  |tagcreation| %>
  <tr>
        <td><%= tagcreation.producttitle %></td>
        <td><%= tagcreation.productoption %></td>
        <td><%= tagcreation.productvalue %></td>
    </tr>
    <% end %>
  </table>
<br/>
 <table caption ="Customer Details" border ="1" >
   <tr> <td> <%= form.label :customertype %>
    <%= form.select :customertype, ["Guest","Existing Customer"] %></td>
<td>
    <%= form.label :customername %>
    <%= form.text_field :customername %></td><td>
    <%= form.label :customeremail %>
    <%= form.text_field :customeremail %></td>
     <%= form.hidden_field :publish , value:'No' %>
      <%= form.hidden_field :productid , value:'1' %>
         <%= form.hidden_field :reviewid ,value:'1' %>
  </tr>
</table><br/><br/>

<table border="1"><tr><td colspan="2">
    <%= form.label :reviewrating %>    
    <%= form.radio_button :reviewrating,'1' %>1<%= form.radio_button :reviewrating,'2' %>2<%= form.radio_button :reviewrating,'3' %>3<%= form.radio_button :reviewrating,'4' %>4<%= form.radio_button :reviewrating,'5' %>5
   </td></tr>
    <tr>  <td>
    <%= form.label :reviewbody %></td><td align="center">
    <%= form.text_area :reviewbody,:cols => 30, :rows => 5 %>
 </td>
 </tr>
  </table >
  <div>
  <%= form.fields_for  :customerreviewtags do |g| %>
    <%= g.label :tag %></td><td align="center">
      
    <%= g.text_field :producttag %>
<% end %>
</div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/customerreviews/edit.html.erb
<center><h1>Editing Customerreview</h1></center>

<%= render 'form', customerreview: @customerreview %>
   <%= form.label :publish %>
    <%= form.select :publish ,["yes","no"] %>
<%= link_to 'Show', @customerreview %> |
<%= link_to 'Back', customerreviews_path %>

app/views/customerreviews/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Customerreviews</h1>
<h2>Refine Your Search : </h2>
<%= form_for "", url: customerreviews_path, role: "Search", method: :get do %>
<%= text_field_tag :search, @search_term, placeholder: "Search Title..." %>
<% end %>
<br/>
<div style="align:center">
    <% @tagcreations.each do |tagcreation| %>
<div class="card" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title"><th> <%= tagcreation.producttitle %></th></h5>
    <h6 class="card-subtitle mb-2 text-muted"> 
     <%= tagcreation.productoption %> : <%= tagcreation.productvalue %>
         <%= tagcreation.productoption1 %>:  <%= tagcreation.productvalue1 %>
        <%= tagcreation.productoption2 %>: <%= tagcreation.productvalue2 %>
        </h6>  
    <p class="card-text"> 
        <%= link_to 'New Customerreview', new_customerreview_path(tagcreation) %></td>
    </tr></p>
  </div>
</div>     
    <% end %>
  </div>
      


<br>
<%= will_paginate @tagcreations, renderer: BootstrapPagination::Rails  %>

app/views/customerreviews/new.html.erb
<center><h1>New Customerreview</h1></center>
<p id="notice"><%= notice %></p>
<%= render 'form', tagcreation: @tagcreation , customerreview: @customerreview %>

<%= link_to 'Back', customerreviews_path %>

app/views/customerreviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Customertype:</strong>
  <%= @customerreview.customertype %>
</p>

<p>
  <strong>Customername:</strong>
  <%= @customerreview.customername %>
</p>

<p>
  <strong>Customeremail:</strong>
  <%= @customerreview.customeremail %>
</p>

<p>
  <strong>Reviewrating:</strong>
  <%= @customerreview.reviewrating %>
</p>

<p>
  <strong>Reviewbody:</strong>
  <%= @customerreview.reviewbody %>
</p>

<p>
  <strong>Publish:</strong>
  <%= @customerreview.publish %>
</p>

<p>
  <strong>Productid:</strong>
  <%= @customerreview.productid %>
</p>

<p>
  <strong>Reviewid:</strong>
  <%= @customerreview.reviewid %>
</p>

<%= link_to 'Edit', edit_customerreview_path(@customerreview) %> |
<%= link_to 'Back', customerreviews_path %>