config/routes.rb
Rails.application.routes.draw do
  resources :productlists
  get '/productlists', :to => 'productlists#index'
  resources :customerreviews do
    resources :customerreviewtags
  end
  resources :tagcreations do
  collection do 
    get :export
    post :import , only: %w(import), controller: "tagcreations"
  end
end


  get '/tagcreations', :to => 'tagcreations#index'
  get '/products', :to => 'products#index'
  root :to => 'home#index'

  resource :marketing_activities, only: [:create, :update] do
    patch :resume
    patch :pause
    patch :delete
    post :republish
    post :preload_form_data
    post :preview
    post :errors
  end
  mount ShopifyApp::Engine, at: '/'
# frozen_string_literal: true

namespace :app_proxy do
  root action: 'index'
  # simple routes without a specified controller will go to AppProxyController

  # more complex routes will go to controllers in the AppProxy namespace
  #   resources :reviews
  # GET /app_proxy/reviews will now be routed to
  # AppProxy::ReviewsController#index, for example
end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/tagcreation.rb
class Tagcreation < ApplicationRecord
	 validates :producttag, presence: true
	 validates :producttag, uniqueness: { scope: [:producttitle, :productoption, :productvalue, :productoption1, :productvalue1, :productoption2, :productvalue2], message: "The Tag already exist" }

def self.search_by(search_term)
	where("LOWER(producttitle) like :search_term", search_term: "%#{search_term.downcase}")
end
end

app/controllers/tagcreations_controller.rb
class TagcreationsController < ApplicationController
  before_action :set_tagcreation, only: [:show, :edit, :update, :destroy]

  # GET /tagcreations
  # GET /tagcreations.json
  def index
    @tagcreations = Tagcreation.paginate(page: params[:page], per_page: 6)    
  end

  # GET /tagcreations/1
  # GET /tagcreations/1.json
  def show
  end

  # GET /tagcreations/new
  def new
    @tagcreation = Tagcreation.new
  end

  # GET /tagcreations/1/edit
  def edit
  end

  # POST /tagcreations
  # POST /tagcreations.json
  def create
    @tagcreation = Tagcreation.new(tagcreation_params)

    respond_to do |format|
      if @tagcreation.save
        format.html { redirect_to @tagcreation, notice: 'Tagcreation was successfully created.' }
        format.json { render :show, status: :created, location: @tagcreation }
      else
        format.html { render :new }
        format.json { render json: @tagcreation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tagcreations/1
  # PATCH/PUT /tagcreations/1.json
  def update
    respond_to do |format|
      if @tagcreation.update(tagcreation_params)
        format.html { redirect_to @tagcreation, notice: 'Tagcreation was successfully updated.' }
        format.json { render :show, status: :ok, location: @tagcreation }
      else
        format.html { render :edit }
        format.json { render json: @tagcreation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tagcreations/1
  # DELETE /tagcreations/1.json
  def destroy
    @tagcreation.destroy
    respond_to do |format|
      format.html { redirect_to tagcreations_url, notice: 'Tagcreation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

#Export the tag creation template for vendor
  def export
  workbook = RubyXL::Workbook.new
  worksheet = workbook.add_worksheet('Sheet')
  worksheet.sheet_name = 'CustomTag'
  worksheet.add_cell(0, 0, 'ProductTitle')
 # worksheet.sheet_data[0][0].change_font_bold(true)
  worksheet.add_cell(0, 1, 'Product Option1') 
 # worksheet.sheet_data[0][1].change_font_bold(true) 
  worksheet.add_cell(0, 2, 'ProductValue1') 
  #worksheet.sheet_data[0][3].change_font_bold(true)
   worksheet.add_cell(0, 3, 'Product Option2') 
 # worksheet.sheet_data[0][1].change_font_bold(true) 
  worksheet.add_cell(0, 4, 'ProductValue2') 
  #worksheet.sheet_data[0][3].change_font_bold(true)
   worksheet.add_cell(0, 5, 'Product Option3') 
 # worksheet.sheet_data[0][1].change_font_bold(true) 
  worksheet.add_cell(0, 6, 'ProductValue3') 
  #worksheet.sheet_data[0][3].change_font_bold(true)
  worksheet.add_cell(0, 7, 'ProductTag') 
  #worksheet.sheet_data[0][5].change_font_bold(true)
  workbook.worksheets.delete(workbook['Sheet1'])
  send_data workbook.stream.string, filename: "customtag.xlsx", disposition: 'attachment', type: 'application/excel'
  end


  #to import the tags from user
def import
   file = params[:file]
  begin
    file_ext = File.extname(file.original_filename)
   # raise "Unknown file type: #{file.original_filename}" unless [".xls", ".xlsx"].include?(file_ext)
    spreadsheet = (file_ext == ".xls") ? Roo::Excel.new(file.path) : Roo::Excelx.new(file.path)
    #header = spreadsheet.row(1)
    ## We are iterating from row 2 because we have left row one for header
    (2..spreadsheet.last_row).each do |i|
         Tagcreation.create(producttitle: spreadsheet.cell(i,1), productoption: spreadsheet.cell(i,2), 
          productvalue: spreadsheet.cell(i,3), productoption1: spreadsheet.cell(i,4), 
          productvalue1: spreadsheet.cell(i,5), productoption2: spreadsheet.cell(i,6),
           productvalue2: spreadsheet.cell(i,7),  producttag: spreadsheet.cell(i,8))
    end
    flash[:notice] = "Records Imported" 
    respond_to do |format|
      format.html { redirect_to tagcreations_url, notice: 'Tagcreation was  Imported.' }
      format.json { head :no_content }
    end          

  end
 end
  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tagcreation
      @tagcreation = Tagcreation.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tagcreation_params
      params.require(:tagcreation).permit(:producttitle, :productoption, :productvalue, :productoption1, :productvalue1, :productoption2, :productvalue2, :producttagid, :producttag)
    end
end

app/helpers/tagcreations_helper.rb
module TagcreationsHelper
end

app/views/tagcreations/_form.html.erb
<%= form_with(model: tagcreation, local: true) do |form| %>
  <% if tagcreation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tagcreation.errors.count, "error") %> prohibited this tagcreation from being saved:</h2>

      <ul>
        <% tagcreation.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 <div class ="container">
<div class="well sidebar-nav"> 
<table border = 1>
  <thead>
    <tr ><th>  <div class="field">
    <%= form.label :Product_Title %>
  </div>

  <th><div class="field">
    <%= form.label :Product_Option1 %>
  </div></th>

  <th><div class="field">
    <%= form.label :Product_Value %>
  </div></th>
 <th><div class="field">
    <%= form.label :Product_Option2 %>
  </div></th>

  <th><div class="field">
    <%= form.label :Product_Value %>
  </div></th> <th><div class="field">
    <%= form.label :Product_Option3 %>
  </div></th>

  <th><div class="field">
    <%= form.label :Product_Value %>
  </div></th>
</tr>
   </thead>
  <tbody>
<tr><td>
  <div class="field">
  <%= form.collection_select :producttitle ,Productlist.order(:title), :title, :title %>
</div></td>
<td><div class="field">
    <%= form.collection_select :productoption ,Productlist.order(:option1), :option1, :option1 %>
  </div></td>
  <td><div class="field">
    <%= form.collection_select :productvalue ,Productlist.order(:option1val), :option1val, :option1val %>
  </div></td>
  <td><div class="field">
    <%= form.collection_select :productoption1 ,Productlist.order(:option2), :option2, :option2 %>
  </div></td>
  <td><div class="field">
    <%= form.collection_select :productvalue1 ,Productlist.order(:option2val), :option2val, :option2val %>
  </div></td>
  <td><div class="field">
    <%= form.collection_select :productoption2 ,Productlist.order(:option3), :option3, :option3 %>
  </div></td>
   <td><div class="field">
    <%= form.collection_select :productvalue2 ,Productlist.order(:option3val), :option3val, :option3val %>
  </div></td>
</tr>
</tbody>
</table>
<br/><br/>  
 <%= form.label :producttag %> : 
<div class="input-group mb-3">
  <div class="input-group-prepend">
    <button class="btn btn-outline-secondary" type="button" >Add</button>
  </div>
   <%= form.text_field :producttag %>

</div>

</div>
</div>
  <!---------------------------add del-------------------------------------------------
  <div class="field">
<div class="container">
    <div class="row clearfix">
      <div class="col-md-12 table-responsive">
      <table class="table table-bordered table-hover table-sortable" id="tab_logic">
        <thead>
          <tr >
            <th class="text-center">
            </td> </th>
              </thead>
          <tbody>
            <tr id='addr0' data-id="0" class="hidden">
            <td data-name="name"><input type="text" name='name0'  placeholder='Name' class="form-control"/>

 <td data-name="del"> <button type = "button" name="del0" class='btn btn-danger glyphicon glyphicon-remove row-remove'><span aria-hidden="true">×</span></button>
                        </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
    <a id="add_row" class="btn btn-primary float-right">Add Row</a>
</div>

  </div>
-----------------end---------------------------------------------->

  <div class="actions" align="right" >
    <%= form.submit %>
  </div>
<div class="actions" align="left"  > 
   <%= link_to 'Back', tagcreations_path %>   
  </div>
<% end %>

app/views/tagcreations/edit.html.erb
<h1>Editing Tagcreation</h1>

<%= render 'form', tagcreation: @tagcreation %>

<%= link_to 'Show', @tagcreation %> |
<%= link_to 'Back', tagcreations_path %>

app/views/tagcreations/index.html.erb
<div class="container" align="center">
     <div class="row">
        <div class="col-lg-9">
          <div class="well sidebar-nav">
       <b> Set Tag through </b> <%=radio_button_tag('tag_flag','online',true, onClick:"  document.getElementById('offline').style.visibility = 'hidden'; 
             document.getElementById('online').style.visibility = 'visible';") %>   Online
            <%=radio_button_tag('tag_flag','offline',false, onClick:"  document.getElementById('online').style.visibility = 'hidden'; 
             document.getElementById('offline').style.visibility = 'visible';") %>   Offline
          </div>
        </div>
      </div>
  </div>
   <div id ="online" style="visibility: visible;justify-content: center;">

<table border = 1 align="center">
  <tr>New Online Tagcreation   :   <%= link_to 'Cilck Here', new_tagcreation_path %><br/></tr>
        <tr><th> <i class="glyphicon glyphicon-exclamation-sign"></i> Instructions: </th>
        </tr>
        <tr>
          <td> <ol type ="1">
            <li>Create a New Tag for productwise</li>
            <li>List of Suggested Tags available for different categories for Reference</li>
            <li>Can create upto five tags for each</li>
           
          </ol></td>
        </tr>
        </table>
</div>
<div id ="offline" style="visibility: hidden;justify-content: center;">
  <div class ="container">
    <div class="well sidebar-nav"> 
<h5>Download the Template   :       <i class="glyphicon glyphicon-upload"></i> <%= link_to "Click Here", export_tagcreations_path %> 
  <br/>
  <%= form_tag import_tagcreations_path, multipart: true do %>
       Upload the file :<%= file_field_tag :file %> </h5>
<br/>
  <%= submit_tag "Import", :class=> "btn" %>

  </div>
      <table border = 1 align="center">
        <tr><th><i class="glyphicon glyphicon-exclamation-sign"></i> Instructions: </th>
        </tr>
        <tr>
          <td> <ol type ="1">
            <li>Download the Excel Template</li>
            <li>List of Suggested Tags available for different categories for Reference</li>
            <li>Fill out the Template with the sheet Custom tag</li>
            <li>Upload The File</li>
          </ol></td>
        </tr>
        </table>
    </div>
  </div>
<!---------------------------------------------------->
<p id="notice"><%= notice %></p>
<div class="list-group">
<table class="table table-hover" border = 1  >
  <thead>
    <tr>
      <th>Product title</th>
      <th>Product option1</th>
      <th>Product option1 value</th>
     <th>Product option2</th>
      <th>Product option2 value</th>
      <th>Product option3</th>
      <th>Product option3 value</th>
      <th>Producttag</th>
      <th colspan="3"></th>
    </tr>
  </thead>
   
  <tbody>
    <% @tagcreations.each do |tagcreation| %>
      <tr>
        <td><%= tagcreation.producttitle %></td>
        <td><%= tagcreation.productoption %></td>
        <td><%= tagcreation.productvalue %></td>
        <td><%= tagcreation.productoption1 %></td>
        <td><%= tagcreation.productvalue1 %></td>
        <td><%= tagcreation.productoption2 %></td>
        <td><%= tagcreation.productvalue2 %></td>
        <td><%= tagcreation.producttag %></td>
        <td><%= link_to 'Update', edit_tagcreation_path(tagcreation) %></td>
        <td><%= link_to 'Delete', tagcreation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br>
<% end %>
<%= will_paginate @tagcreations, renderer: BootstrapPagination::Rails  %>

app/views/tagcreations/new.html.erb
<h1>New Tagcreation</h1>

<%= render 'form', tagcreation: @tagcreation %>

app/views/tagcreations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Producttitle:</strong>
  <%= @tagcreation.producttitle %>
</p>

<p>
  <strong>Productoption:</strong>
  <%= @tagcreation.productoption %>
</p>

<p>
  <strong>Productvalue:</strong>
  <%= @tagcreation.productvalue %>
</p>

<p>
  <strong>Producttagid:</strong>
  <%= @tagcreation.producttagid %>
</p>

<p>
  <strong>Producttag:</strong>
  <%= @tagcreation.producttag %>
</p>

<%= link_to 'Edit', edit_tagcreation_path(@tagcreation) %> |
<%= link_to 'Back', tagcreations_path %>